@baseUrl = http://localhost:3000
@userId = 5fd1474d-f419-4bee-9727-b628a9032e4c
@customertoken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbWNnM3Npc2IwMDAwdGJ5azdreTVsdmN5IiwiZW1haWwiOiJsdWtlYmV0aWthQGdtYWlsLmNvbSIsInJvbGUiOiJDVVNUT01FUiIsImlhdCI6MTc1MTEwNjgyOCwiZXhwIjoxNzUxMTkzMjI4fQ.3MlC-VmTdyLxkgibJXDP7ZEpViUt4L97wAN24VoZAD0
@adminToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbWNlYWNtcm0wMDAxdGJsb3JtaWF5dHdnIiwiZW1haWwiOiJhZG1pbkBzaG9waWUuY29tIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzUxMTA2Mjc2LCJleHAiOjE3NTExOTI2NzZ9.3Gz3dlkjSqwge-BE-aeXpQfQDlOd_xSZiGV6HDXLyWk

### Register a new customer
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "email": "w41314343@gmail.com",
  "password": "user123456",
  "phone": "0798332744",
  "name": "Luke",
  "role": "AGENT"
}

### Register a new admin
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "email": "kivindukilonzo@gmail.com",
  "password": "admin123456",
  "phone": "0798678778",
  "name": "Admin ",
  "role": "ADMIN"
}

### Login with valid credentials
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "rockx2060@gmail.com",
  "password": "rockx2060@gmail.com"
}

### Login with admin credentials
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "admin@shopie.com",
  "password": "admin123456"
}

### Login with wrong password
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "customer@shopie.com",
  "password": "wrongpassword"
}

### Request password reset
POST {{baseUrl}}/auth/forgot-password
Content-Type: application/json

{
  "email": "kivindukilonzo@gmail.com"
}

### Change password (requires authentication)
POST {{baseUrl}}/auth/reset-password
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "currentPassword": "newpassword123",
  "newPassword": "password123"
}
### Get user profile
GET {{baseUrl}}/auth/profile
Content-Type: application/json
Authorization: Bearer {{customertoken}}