@baseUrl = http://localhost:3000
//add location
POST {{baseUrl}}/locations
Content-Type: application/json

{
  "name": "Makueni",
  "address": "123 Main St",
  "city": "Nairobi",
  "country": "Kenya",
  "isActive": true
}